bench:
	g++ -std=c++11 -g -Wall BST.hpp BSTIterator.hpp BSTNode.hpp RST.hpp countint.cpp RST.hpp benchtree.cpp -o test

myTest:
	g++ -std=c++11 -g -Wall BST.hpp BSTIterator.hpp BSTNode.hpp RST.hpp countint.cpp myTest.cpp -o myTest

